FEATURES_FILE = "/train-features.csv"
CLASS_KEYWORD = "class"
TEST_KEYWORD = "test"
FILE_SEPARATOR = "_"

MAX_TREE_DEPTH = 5
MIN_TREE_DEPTH = 1

POPULATION_SIZE = 200

TOURNAMENT_SIZE = 3

CROSS_PROBABILITY = 0.5
MUTATE_PROBABILITY = 0.2
GENERATION_COUNT = 50

BASE_FEATURE_NAME = "Feature"